#pragma once

typedef enum _MEMORY_OPERATION_TYPE {
    MEMORY_OP_LINK,
    MEMORY_OP_UNLINK,
    MEMORY_OP_SCAN,
    MEMORY_OP_PROTECT
} MEMORY_OPERATION_TYPE;

typedef enum _DRIVER_COMMAND {
    CMD_INITIALIZE,
    CMD_POPULATE_VAD,
    CMD_LINK_MEMORY,
    CMD_UNLINK_MEMORY,
    CMD_CHANGE_PROTECTION
} DRIVER_COMMAND;